-- Initial schema for Frawly's D1 (SQLite) backend. SQLite/D1 translation of
-- what was previously a Postgres schema (see the repo history) - same
-- design: the containers table IS the registry (a row existing means its
-- id is registered), so add/remove-id and edit-fields are the same row.
create table containers (
  -- User-assigned, e.g. "P-3" or "G-12" - never generated by the app.
  id text primary key check (id glob '[A-Za-z0-9]*-[0-9]*'),
  -- Derived from id (the part before the first "-"). SQLite has no
  -- split_part(); substr()/instr() do the same job.
  prefix text generated always as (substr(id, 1, instr(id, '-') - 1)) stored,
  -- ISO "YYYY-MM-DD", null when vacant/empty. SQLite has no native date
  -- type - stored as text, same format the app already uses.
  date text,
  status text not null default 'vacant'
    check (status in ('vacant', 'frozen', 'construction')),
  -- Ordered list of {name, quantity} as a JSON array (D1/SQLite has no
  -- jsonb type - json_valid() is the closest equivalent guard).
  ingredients text not null default '[]' check (json_valid(ingredients)),
  created_at text not null default (datetime('now')),
  updated_at text not null default (datetime('now'))
);

create index containers_status_idx on containers (status);
create index containers_prefix_idx on containers (prefix);
create index containers_date_idx on containers (date);

create trigger containers_set_updated_at
  after update on containers
  for each row
  begin
    update containers set updated_at = datetime('now') where id = new.id;
  end;
