import 'container_status.dart';
import 'ingredient.dart';

/// A registered freezer container. The registry and per-container data are
/// the same row server-side (see the initial schema migration) - a
/// [FreezerContainer] existing at all means its id is in the registry.
///
/// Named `FreezerContainer` (not `Container`) to avoid colliding with
/// Flutter's own `Container` widget, which is used throughout the UI.
class FreezerContainer {
  FreezerContainer({
    required this.id,
    required this.date,
    required this.status,
    required this.ingredients,
  });

  /// User-assigned, e.g. "P-3" or "G-12". Never generated by the app.
  final String id;

  /// Null when [status] is vacant.
  final DateTime? date;
  final ContainerStatus status;
  final List<Ingredient> ingredients;

  /// The part of [id] before the first "-", e.g. "P" for "P-3".
  String get prefix => id.split('-').first;

  String get ingredientSummary {
    if (ingredients.isEmpty) return 'No ingredients';
    return ingredients
        .map((i) => i.quantity.trim().isEmpty ? i.name : '${i.name} (${i.quantity})')
        .join(', ');
  }

  factory FreezerContainer.fromRow(Map<String, dynamic> row) {
    final rawIngredients = row['ingredients'] as List<dynamic>? ?? const [];
    return FreezerContainer(
      id: row['id'] as String,
      date: row['date'] == null
          ? null
          : DateTime.parse(row['date'] as String),
      status: ContainerStatus.fromValue(row['status'] as String),
      ingredients: rawIngredients
          .whereType<Map<Object?, Object?>>()
          .map((e) => Ingredient.fromJson(Map<String, dynamic>.from(e)))
          .toList(),
    );
  }

}
