-- Initial schema for Frawly's Supabase backend (Freezer Log).
--
-- The container registry and each container's data are the same table:
-- a row's existence *is* registry membership, so adding/removing an id and
-- editing its date/status/ingredients are all just writes to this one row -
-- removing a row naturally deletes its data with it, with nothing to keep
-- in sync across tables.
--
-- No RLS/auth yet (see CLAUDE.md) - the app currently has no user auth
-- wired up, so access is fully open via the anon key, same as
-- SplitBalance/LaPlanif today. Add RLS policies here if/when auth lands.
create table containers (
  -- User-assigned, e.g. "P-3" or "G-12" - never generated by the backend.
  id text primary key check (id ~ '^[A-Za-z0-9]+-[0-9]+$'),
  -- Derived from id (the part before the first "-"), stored+generated so it
  -- can be indexed/filtered on directly instead of re-parsing id on every
  -- query.
  prefix text generated always as (split_part(id, '-', 1)) stored,
  -- Null when vacant/empty.
  date date,
  status text not null default 'vacant'
    check (status in ('vacant', 'frozen', 'construction')),
  -- Ordered list of {name: string, quantity: string}. Kept as jsonb on the
  -- container row (not a separate table) so a bulk filling/empty affecting
  -- many containers stays a single atomic UPDATE ... WHERE id IN (...) per
  -- PostgREST request instead of needing per-row child-table sync - see
  -- CLAUDE.md's "avoid RPCs when a client-side query can do the job".
  ingredients jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index containers_status_idx on containers (status);
create index containers_prefix_idx on containers (prefix);
-- Ordering the home list by date ascending with nulls first (vacant
-- containers surface first) is the app's one hot-path query - index it.
create index containers_date_idx on containers (date);

create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger containers_set_updated_at
  before update on containers
  for each row execute function set_updated_at();

-- Baseline grants a bare local Postgres (via `supabase start`) doesn't get
-- automatically the way a hosted Supabase project does - see
-- SplitBalance's grant_default_table_privileges migration for the same
-- fix and its full rationale. RLS is not enabled above, so these grants
-- are effectively the only access control right now (open via anon key).
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public
  to anon, authenticated, service_role;
grant usage, select on all sequences in schema public
  to anon, authenticated, service_role;
alter default privileges in schema public
  grant select, insert, update, delete on tables to anon, authenticated, service_role;
alter default privileges in schema public
  grant usage, select on sequences to anon, authenticated, service_role;
